### ISSUE TITLE
How to display validation performance?

### ISSUE THREAD

**Issue by DrXZenG** [interpretml/interpret#164] opened 2020-09-18 14:52 UTC
Hello,

Thanks for sharing this great work!
ExplainableBoostingClassifier has a default parameter for early stopping and validation split. I am wondering if the performance on the validation dataset can be display in some way. 
Thank you in advance!

**Comment by interpret-ml** [comment] 2020-10-02 22:14
Hi @1230pitchanqw ,

Thanks for bringing this up. We currently log the validation performance of every 10th epoch in our logging system. You can enable this by running the following utility function at the top of your file:

```python3
from interpret.develop import register_log

register_log('output.txt', level="DEBUG")
```

However, the logs contain other messages captured during the training process as well. We currently don't support only logging the validation metric, but can look into this in the future. Glad to hear you're enjoying the package!

-InterpretML Team

**Comment by paulbkoch** [comment] 2023-01-23 19:36
Closing this issue as it seems to be a duplicate of issue https://github.com/interpretml/interpret/issues/7 .

**Closed by paulbkoch** 2023-01-23 19:36 UTC
