### ISSUE TITLE
Graphs for show(emb_global) don't update, only stay on Overall Imprtance

### ISSUE THREAD

**Issue by davidparks21** [interpretml/interpret#108] opened 2020-01-27 19:53 UTC
I'm trying to run through the first demo notebook `Interpretable machine learning models for binary classification`, but I'm finding that the `show(emb.explain_global())` doesn't update when you select different features, it remains on the Overall Importance graph.

![image](https://user-images.githubusercontent.com/964997/73208541-81fc8380-40fb-11ea-9997-b0ba1440de05.png)

I've tried this on a local Python 3.7.3 Jupyter notebook. On Google Colab I can get the ClassHistogram example to plot, but the rest of the examples fail to plot without any discernible error message.

**Comment by interpret-ml** [comment] 2020-02-03 18:57
Hi @davidparks21, 

Thank you for reporting this! We're struggling to reproduce this on our end, especially for your local failure on Python 3.7.3. Have you tried waiting ~15-20 seconds? Sometimes the first graph update can be delayed as the graphs are rendered.

Could you share a bit of information with us about your local environment?

Operating System:

Interpret library Version (run ```pip show interpret``` or inside an ipython console, ```import interpret``` then ```interpret.__version__```): 

Additionally, on your local environment, could you try running the following code at the start of the notebook, and see if the updates work any better?

```python3
from interpret.provider import InlineProvider
from interpret import set_visualize_provider

set_visualize_provider(InlineProvider())
```

This changes the rendering logic we use under the hood, which might work better in your situation.

Thanks so much for the help!
-InterpretML Team

**Comment by guomengzhuo** [comment] 2020-03-04 08:15
Hi, @interpret-ml 
Is it possible to get EPS or PDF format figures? I just find a button to download a png format figure with _show()_ command.

**Comment by interpret-ml** [comment] 2020-07-22 17:53
Hi @davidparks21 , 

We've made a few improvements in our latest release of interpret (v0.2.0), which improves our visualization experience (especially in cloud environments). Closing this issue for now, as we are unable to reproduce this, but please give our latest release a try and feel free to re-open it if this is still a problem. 

@guomengzhuo , For the most part, our graphs are all plotly figures, which provide saving functionality out of the box to html and png. Plotly also provides some extra utilities for saving graphs to alternate formats through their Orca library: https://github.com/plotly/orca . 

You can get the underlying plotly figure for any of our visualizations by using the ```visualize``` method on any explanation:

```python3
ebm_local = ebm.explain_local(X_test[:5], y_test[:5])
plotly_fig = ebm_local.visualize(0)  # This is the plotly figure for visualization of the 0th datapoint's local explanation
```

Once you have Orca installed, you can simply save this figure as a PDF with the following code:

```
plotly_fig.write_image("images/fig0.pdf") 
```

Closing this issue for now, but please feel free to re-open if there are continued errors on v0.2.0+. 

-InterpretML Team

**Closed by interpret-ml** 2020-07-22 17:53 UTC

**Comment by monika393** [comment] 2021-10-03 08:22
yeah me too faced same issue on google collab
