### ISSUE TITLE
EBM log-link global_explainer plots on inverse link scale?

### ISSUE THREAD

**Issue by invalidarg** [interpretml/interpret#452] opened 2023-07-12 13:37 UTC
Hi,

I have an EBM-regressor with tweedie objective and log-link

```
ebm = ExplainableBoostingRegressor(
        objective="tweedie_deviance:variance_power=1.001",
 )
ebm.fit(...)
show(ebm.explain_global())
```

The plots are currently on log-link scale. But I would prefer to have the plots on inv-link scale instead. Is that possible?

**Comment by paulbkoch** [comment] 2023-07-28 18:58
Hi @invalidarg -- The short answer is that it's possible in theory to do this, but our package does not support this out of the box yet.  I would like to have UI to do this someday, but it's not on our immediate horizon, so if it were to be implemented in the near term it would need to be a PR.

There are some caveats too in that you lose the additive property between graphs represented this way.  If you wanted to do it yourself for your own UI, the way to achieve this would be to take the intercept, add it to each bin in the graph, apply the inverse link on each bin, and then graph the results.

There's some information on how EBMs are represented internally:
https://interpret.ml/docs/ebm-internals-regression.html

**Comment by fsaforo1** [comment] 2023-11-09 02:31
@paulbkoch Is it possible to get `ebm.predict_and_contrib(...)` output on the inv-link scale instead?

**Comment by paulbkoch** [comment] 2023-11-09 21:47
Hi @fsaforo1 -- We're currently missing the equivalent of the "output" parameter that exists in the ExplainableBoostingClassifier.  Before alternative objectives were added this wasn't an issue since RMSE regression uses the identity link.  For now there are a number of ways that you could get the original scores before the inv-link is applied.

1) We currently only support objectives that use either the identity or the log link.  I'm assuming you aren't using an identity link since then you'd already have the answer, which means if you call np.log on the predictions you'll get back the original scores.  We also have a private utility function that I'm considering making public to apply the link function if you want to solve this in a way that should work with future link functions: https://github.com/interpretml/interpret/blob/b2cd0ce053962bd0b17db64de268c55fa9cabb29/python/interpret-core/interpret/utils/_link.py#L8

2) The per-term scores that are returned by ebm.predict_and_contrib in index 1 of the tuple can simply be added to get the pre-inv-link prediction.

**Comment by fsaforo1** [comment] 2023-11-10 10:44
Thank you for your prompt response, and I apologize for any confusion earlier. Presently, when using a model with a log link, such as Tweedie, the method `ebm.predict_and_contrib(...)` provides an output (specifically at index 1) on the linear predictor scale meaning the expression `np.exp(ebm.predict_and_contrib(...)[1].sum(1) + ebm.intercept_)` equates to `ebm.predict(...)`.

My request is to adjust this so that the `ebm.predict_and_contrib(...)[1].sum(1)` directly corresponds to `ebm.predict(...)`, without the need to apply `np.exp`. In other words, I'm looking for a scenario where `ebm.predict_and_contrib(...)[1].sum(1) + ebm.intercept_ = ebm.predict(...)`

**Comment by paulbkoch** [comment] 2023-11-11 18:03
With a log link the terms are not additive in the response scale.  You could multiply them since:  exp(f0_score + f1_score + intercept) = exp(f0_score) * exp(f1_score) * exp(intercept)

If you want additive terms on the response scale as we have for MSE regression, you need to use an identity link.

**Comment by fsaforo1** [comment] 2023-11-13 14:44
Thanks @paulbkoch you can close this sub-issue. We have some internal processes that require additive explanations for all our models including those with non-identity link. I would just use SHAP's `PermuatationExplainer` for now.

**Closed** 2023-11-15 01:20 UTC
