### ISSUE TITLE
Excluding certain variables for validation/training

### ISSUE THREAD

**Issue by mortennyb** [interpretml/interpret#208] opened 2021-02-17 17:36 UTC
Hello,

Thanks for the excellent package. I've recently come across a problem in a regression design; I cannot look at the effect of any time-varying group variable without the fixed effect from the group+year "leaking into" it. It sounds abstract but I think it's an important problem in many applied settings. It is probably easiest to explain with an example.

I am trying to predict an outcome y, say individual happiness from a global survey. I have many individual observations in many countries and years. I want to add an effect of "living in China", so I add a country fixed effect (i.e. a variable China=0 or 1). I also want to see the effect of some societal country-specific variable -- say population, which changes slightly over time. I don't want the pure effect of "China in 2015", because I'm more interested in the population correlation than the "China+year" correlation.

When I do this, there is a problem. China is the only country with 1B+ inhabitants, so all the "population" values near 1B will uniquely identify China. This means that e.g. population=1.371B will uniquely identify "China in 2015": since I have many individuals in China in 2015, the model is able to use population=1.371B as a "China in 2015"-variable. Any high/low average happiness in China in 2015 is correlated to population=1.371B. If people in China in 2015 were happy, my model says that population=1.371B correlates with very high happiness (which correlates slightly better than the China=1 variable because the year-change is added in). Similarly, 1.386B people will uniquely identify "China in 2017", etc. So no matter what population actually correlates to, it has now become the "China+year" fixed effect (which I didn't want). The example is strongest if there are no other country-level data points around, but it happens even in crowded areas, I believe.

A solution to this would be to do cross-validation with all "country x in year y" observations in the same training/learning sets. Then the model wouldn't be able to identify China in a certain year based on population, and the China correlations would go into the China=1 variable, presumably. So I'm wondering if this is possible at all. Thanks!

**Comment by mortennyb** [comment] 2021-02-17 19:28
Sorry for the wall of text. What I'm asking for is whether you have added a feature to choose custom validation sets, as mentioned here: https://github.com/interpretml/interpret/issues/31

**Comment by paulbkoch** [comment] 2023-01-27 06:56
Closing this issue since it is a duplicate of Issue #31.  We'll post any updates for custom validation sets in that issue.

**Closed by paulbkoch** 2023-01-27 06:56 UTC
