### ISSUE TITLE
Relation between EBM scores and model parameters

### ISSUE THREAD

**Issue by rickymagner** [interpretml/interpret#563] opened 2024-07-18 03:17 UTC
Hi, I'm trying to understand better how to interpret the parameters of a fit EBM, like done in the example [here](https://interpret.ml/docs/ebm.html). In short my questions are:

1. What are the default $f_j$ functions used in the EBM formula for the default implementation of the `ExplainableBoostingClassifier`? Are these linear for the noninteraction terms and quadratic for interaction, and if so, how do the coefficients of the model relate to the scores reported in the graphs? Is it possible to obtain the actual coefficients if these differ?
2. When using `ebm.explain_local`, are the "contribution to the prediction" values exactly the values returned by evaluating the $f_j$'s on the input data? 
3. For the classifier, is the predicted value returned by `predict_proba` the tuple of probability of the predicted classification, i.e. a value `[0.75, 0.25]` reflects 75% chance of label 0 vs 25% label 1? (Is this just logistic regression in the case of no interaction terms?)
4. More of a conceptual question: if I train a model on two features that are totally dependent on each other, the model assigns quite a difference in feature importance to them. Why is that? For example, training on:
```
s = 1000
z = int(s/2) * [0] + int(s/2) * [1]

df = pd.DataFrame({'a': list(range(s)), 'b': reversed(list(range(s))), 'z': z})
```
leads to feature `a` having global "mean absolute score" around 8, whereas `b` has value around 6 in the experiment I tried. For some reason they seem to be orders of magnitude different in importance, but clearly of equal utility in predicting `z`. 

Any links to documentation on these would be great! I browsed a few other conceptual questions in other issues but couldn't find answers to some of these basics.

**Comment by paulbkoch** [comment] 2024-07-20 01:27
Hi @rickymagner -- Answers are:

1. Unlike traditional spline GAMs, EBMs are not constructed using underlying functions. We start by discretizing all the features into bins. We then use boosting to choose the y value scores that get assigned to each bin.  The translation from a particular x value to the corresponding y value is done through a lookup table located at ebm.term_scores_[term_index].  The bin discretization values are located at: ebm.bins_[feature_index]. The global explanations are simply the piecewise constant graphs that result from these two attributes.
2. Yes, the local explanations are identical to the values you get by looking up the y value on the global explanation graphs.  There is an example showing how to determine these, and the corresponding local explanations in https://interpret.ml/docs/ebm-internals-regression.html
3. Yes, predict_proba returns probabilities in the order you indicated.  It is very similar to logistic regression in that we use the logistic function to translate scores into probabilities.  This is also identical to how traditional GAMs work for classification.
4.  There's a slight bias stemming from the consistent initial ordering of features. It's something I've known about, but haven't addressed yet since I figured it would only be observable in extremely simple models using essentially identical features, and shouldn't be an issue for real models.  Since you asked though, I implemented and tested a fix, and the numbers are close to identical afterwards.  I'll include this change in our next release.

**Comment by rickymagner** [comment] 2024-07-20 17:52
Hi @paulbkoch, thanks for your comment. Things are starting to make a bit more sense. I misunderstood the underlying functions as similar to traditional splines, rather than closer to decision trees (piecewise constant functions) that contribute to the final score for each feature (or interaction term). I had a few quick follow-up questions about EBM binary classification:

1. Given a categorical feature that is lopsided (e.g. 95+% label 0 and 5-% label 1, or even more extreme), how important would e.g. upsampling generally be to ensure the model learns the importance of the feature appropriately? Is the model sensitive enough to pick up on these "small" features so that their contribution to the global score is comparable with other features who might have a more balanced distribution of values?
2. In the situation above where there are some "lopsided" binary features mixed in with more balanced ones, how important might it be to normalize the inputs? Before I thought if the model was classical linear, it'd be possible that the features with more 1's might unfairly contribute a larger portion to the global score since they're more plentiful than those with a less common value of 1, but now it sounds like the model might be just fine learning how to weight the $f_j$ tree importance to the global score independent of the feature distribution values, right?

It's good to hear the weird edge case of highly correlated input features would be fixed in the next release. I have some data where some features might be a bit correlated (which I suppose could be pruned in some preprocessing...), so it's nice to know the model in the next version might still be robust in the case those features slip in, at least in the sense that interpreting the relative importance of features would display similar values for similar input features.

**Comment by rickymagner** [comment] 2024-07-20 20:53
Hi @paulbkoch, thanks for sharing your insights. Those are some good points about comparing to GBDTs. I was also wondering about the case where my target labels were dramatically lopsided as well (e.g. binary labels with most 0 and <= 5% 1), since in this case there's a greater risk of the trivial model that always returns 0 which would still have decent accuracy. I'll do a little more experimenting in that vein and see how it goes. Feel free to close this issue as resolved, thanks!

**Comment by paulbkoch** [comment] 2024-07-20 21:23
Hi @rickymagner -- EBMs seem to do ok in these scenarios as well, although I don't think we've carefully compared them to other models when it comes to imbalanced datasets.  At this point there are quite a few outside papers that compare EBMs though, so someone else might have.  The model evaluation for early stopping is done using log loss, which doesn't have the same issues of reaching 100% accuracy.

Closing the issue, but feel free to add more questions if you think of more.

**Closed by paulbkoch** 2024-07-20 21:23 UTC
