### ISSUE TITLE
When Interpret can be used in Kaggle 

### ISSUE THREAD

**Issue by GDGauravDutta** [interpretml/interpret#216] opened 2021-03-25 17:53 UTC
UserWarning: Cloud environment detected (['kaggle', 'ipython-zmq', 'ipython']): viz integration is still experimental.

No viz visible but locally , it's working fine

**Comment by MainRo** [comment] 2021-05-20 13:20
I have the same issue on mybinder

**Comment by paulbkoch** [comment] 2023-01-29 05:06
I think this could be a duplicate of issue https://github.com/interpretml/interpret/issues/172.  If so, that would be fortunate since we have a PR fix for that issue.

**Comment by paulbkoch** [comment] 2023-01-29 05:14
There's at least one Kaggle page that I'm aware of that is using InterpretML.  The warning is also visible there, but the UI is showing up at least:

https://www.kaggle.com/code/parulpandey/explainable-boosting-machines-for-tabular-data/notebook

**Comment by paulbkoch** [comment] 2023-01-29 05:17
There's also an issue regarding mybinder: https://github.com/interpretml/interpret/issues/150

**Comment by paulbkoch** [comment] 2023-02-10 06:30
I just merged https://github.com/interpretml/interpret/pull/210 into the code, which might fix this issue. Will leave this issue open until we have verification.

**Comment by paulbkoch** [comment] 2023-06-07 06:38
There's a new notebook in Kaggle that uses EBMs and the visualizations work there.  Since this seems to be confirmed as working, I'll close this issue.

I can also confirm that mybinder works now.  I added a link to the classification example in mybinder to our README.

Kaggle notebook:
https://www.kaggle.com/code/warcoder/explainable-boosting-machine

**Closed by paulbkoch** 2023-06-07 06:38 UTC
Labels: bug
