### ISSUE TITLE
Error with Extreme Boosting Classifier- Illegal native parameter value in CalcInteractionStrength

### ISSUE THREAD

**Issue by stewartdesoto** [interpretml/interpret#430] opened 2023-05-03 15:38 UTC
I am getting the following exception apparently related to interactions when  using EBM. Interpret version 0.3.2. What could be the cause and remedy?

/lib/python3.9/site-packages/interpret/utils/_native.py:1635, in InteractionDetector.calc_interaction_strength(self, feature_idxs, interaction_flags, min_samples_leaf)
   1626 return_code = native._unsafe.CalcInteractionStrength(
   1627     self._interaction_handle,
   1628     len(feature_idxs),
   (...)
   1632     ct.byref(strength),
   1633 )
   1634 if return_code:  # pragma: no cover
-> 1635     raise Native._get_native_exception(return_code, "CalcInteractionStrength")
   1637 log.info("Fast interaction strength end")
   1638 return strength.value

Exception: Illegal native parameter value in CalcInteractionStrength

**Comment by paulbkoch** [comment] 2023-05-03 17:23
Hi @stewartdesoto -- This is an interesting error.  It indicates a bad parameter value was passed from python to C, but none of the parameters passed to that C function are things that you should be able to influence from our public python interface, so it should be a bug in our code.  I suspect memory corruption of some kind that occurs sometime before calling this function.  I would really like to resolve this.

Probably the best next step would be to enable the debug native library and logging.  To do that, can you insert the following lines in your code before calling anything else in interpret:

```
from interpret.develop import debug_mode
debug_mode(log_filename='log.txt', log_level='INFO', native_debug=True)
```

And the either post any relevant part of the log.txt file here or alternatively email it to us at interpret@microsoft.com

Thanks for reporting this!

**Comment by dimidd** [comment] 2023-05-16 09:53
FWIW, I had the same issue when one of the features was a float, and it was resolved after converting to int.

**Comment by paulbkoch** [comment] 2023-05-16 18:38
Hi @dimidd -- Do you still have access to the dataset where this was failing?  @stewartdesoto and I cycled a bit over email on this issue, but were unable to isolate it sufficiently to resolve it.  I'm still really interested in solving it though!

**Comment by paulbkoch** [comment] 2023-05-16 22:08
I found the bug!  The fix is in develop:
https://github.com/interpretml/interpret/commit/202c723b54df068e730cb0b726c6c14e2afddd51

For the curious, the specific issue was in this line:
Native._make_pointer(np.array(feature_idxs, np.int64), np.int64),

The call to np.array was creating a new python object with a reference count of 1.  The object was passed to _make_pointer which created a native pointer to it, but did not store a python reference to the original np.array.  After the call to _make_pointer the reference to the np.array was decremented to 0, allowing the memory to be reclaimed.  The pointer still existed though and was being passed to the native code.  In most cases the memory would still contain the original contents and everything would work properly.  Every once in a while though, the memory might be overwritten since it had been freed.  In this case the feature indexes would be out of bounds.  The native code checks inputs for consistency whenever possible.  In this case it's likely the garbage indexes were outside the range 0 <= index < len(feature_indexes).  In that case "Illegal native parameter value" is returned which is consistent with what was observed.  The fix is simply to put the feature_idxs array into a local variable that will have validity for the duration of the call to CalcInteractionStrength.

Thank you @stewartdesoto and @dimidd for reporting this issue!  This is a great defect to have resolved.  I'm going to put out a v0.4.1 release to address it shortly.

**Closed by paulbkoch** 2023-05-16 22:08 UTC
Labels: bug

**Comment by paulbkoch** [comment] 2023-05-16 23:54
Version 0.4.1 has been published on PyPI.  If either of you still has access to a dataset that was failing before, it would be good to verify that this release fixes the problem.

**Comment by dimidd** [comment] 2023-05-17 04:51
Thanks, I'll try to upgrade and reproduce

**Comment by dimidd** [comment] 2023-05-17 06:46
So far so good

**Comment by paulbkoch** [comment] 2023-05-18 04:40
Thanks @dimidd!
